### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by sreza4** [Ayzzzzzzzzzzz/DeReel_Instagram#1]
Hi,
Anyway you can make an IPA for this? I really want to remove reels but I am on a non-jailbroken iphone. I am also not very familiar with this stuff so I am a bit lost on doing it myself.

**Comment by Ayzzzzzzzzzzz** [comment]
Im going to try to inject the deb into the app, but I am unsure if its going to work. If it worked I will upload it to the releases tab.

**Comment by Ayzzzzzzzzzzz** [comment]
Okay it’s uploaded now :)
