### ISSUE TITLE
Instagram crashing

### ISSUE THREAD

**Issue by lumen-novum** [Ayzzzzzzzzzzz/DeReel_Instagram#2]
Hello, I've tried the ipa and the deb (arm64 iPhone 14) and whenever I login, Insta crashes without an error message.
If I try to reopen the app, it just brings me back to the login screen.

Do you know why this is happening?

**Comment by Ayzzzzzzzzzzz** [comment]
Hi, I really have no clue why this is happening. Please try to log into Instagram and after that install the tweak. Sadly Instagram changed some things up and reels are still showing up on the home screen, so I will try to fix that too.

**Comment by lumen-novum** [comment]
Unfortunately, it still doesn't work. If it helps, I'm on 17.3 and used Sideloadly to inject the tweak and tried the ipa as well. I also have device logs if you would like those. I really appreciate your help. 🙂

**Comment by Ayzzzzzzzzzzz** [comment]
Hi, sasly I think this version has many problems that I am unable to fix :( you can try out the bhinsta tweak from vlourme if that works for you.

**Comment by Ayzzzzzzzzzzz** [comment]
Sorry, I am unable to fix this Issue on this version.

**Comment by lumen-novum** [comment]
It's okay, thank you for the suggestion. The bhinsta tweak worked for me!
